clean up the readme
cWorksLLC/miniorganize pull request #2
Opened 2024-11-23 17:50 UTC by webbrowser11

ye ye

2024-11-23 18:04 UTC, BDadmehr0 commented
I suggest adding an example for the input path and the expected output structure to make it clearer for users.

2024-11-23 18:09 UTC, BDadmehr0 requested changes

2024-11-23 18:09 UTC, BDadmehr0 commented on README.md
> +unzip the folder and run the .py file and then in the cmd that pops up enter the a full location of the folder you want to organize.
It is better to write words like .py, .exe inside '`words`'.

2024-11-23 18:09 UTC, BDadmehr0 commented on README.md
> +### (non-windows):
non-windows !?

Mac or Linux, or Unix-based systems

2024-11-23 19:08 UTC, webbrowser11 commented
thanks, i will propose to add some of this stuff

2024-11-23 19:10 UTC, webbrowser11 commented
@BDadmehr0 if you go to my repo on that branch and make a pr with these changes, i will accept it and it will be merged here.

2024-11-23 19:11 UTC, webbrowser11 commented
if you want to wait and let me do this therefor make the development time to clean up the readme longer, you can do that too.

2024-11-23 19:29 UTC, BDadmehr0 commented
> @BDadmehr0 if you go to my repo on that branch and make a pr with these changes, i will accept it and it will be merged here.

There's no rush; make the changes whenever you have time.

2024-11-23 19:34 UTC, webbrowser11 commented
i was saying you could do it too, on my repo, so it gets merged to this repo.

2024-11-23 19:34 UTC, webbrowser11 commented
u would be contrib too

2024-11-23 19:40 UTC, BDadmehr0 commented
> u would be contrib too


The problem is that it's currently nighttime in Iran, and I have shut down my system. I won't be able to make any changes for the next 20 hours. If the changes are not made by then, I will take care of it myself.

2024-11-23 21:37 UTC, webbrowser11 commented
k

2024-11-24 01:38 UTC, merged

2024-11-24 01:39 UTC, cWorksLLC commented
Done. I like the changes here.

2024-11-24 03:41 UTC, webbrowser11 commented
nice, might come back to do more tmrw